namespace OpenDPE.Core
{
	partial class Departement
	{
		#region DEPARTEMENTS
		
		private readonly static Departement[] _table = new Departement[]
		{
			new Departement("Ain", "01", ZoneClimatique.H1c),
			new Departement("Aisne", "02", ZoneClimatique.H1a),
			new Departement("Allier", "03", ZoneClimatique.H1c),
			new Departement("Alpes-de-Haute-Provence", "04", ZoneClimatique.H2d),
			new Departement("Hautes-Alpes", "05", ZoneClimatique.H1c),
			new Departement("Alpes-Maritimes", "06", ZoneClimatique.H3),
			new Departement("Ardèche", "07", ZoneClimatique.H2d),
			new Departement("Ardennes", "08", ZoneClimatique.H1b),
			new Departement("Ariège", "09", ZoneClimatique.H2c),
			new Departement("Aube", "10", ZoneClimatique.H1b),
			new Departement("Aude", "11", ZoneClimatique.H3),
			new Departement("Aveyron", "12", ZoneClimatique.H2c),
			new Departement("Bouches-du-Rhône", "13", ZoneClimatique.H3),
			new Departement("Calvados", "14", ZoneClimatique.H1a),
			new Departement("Cantal", "15", ZoneClimatique.H1c),
			new Departement("Charente", "16", ZoneClimatique.H2b),
			new Departement("Charente-Maritime", "17", ZoneClimatique.H2b),
			new Departement("Cher", "18", ZoneClimatique.H2b),
			new Departement("Corrèze", "19", ZoneClimatique.H1c),
			new Departement("Cores-du-Sud", "2A", ZoneClimatique.H3),
			new Departement("Haute-Corse", "2B", ZoneClimatique.H3),
			new Departement("Côte-d'Or", "21", ZoneClimatique.H1c),
			new Departement("Côtes-d'Armor", "22", ZoneClimatique.H2a),
			new Departement("Creuse", "23", ZoneClimatique.H1c),
			new Departement("Dordogne", "24", ZoneClimatique.H2c),
			new Departement("Doubs", "25", ZoneClimatique.H1c),
			new Departement("Drôme", "26", ZoneClimatique.H2d),
			new Departement("Eure", "27", ZoneClimatique.H1a),
			new Departement("Eure-et-Loir", "28", ZoneClimatique.H1a),
			new Departement("Finistère", "29", ZoneClimatique.H2a),
			new Departement("Gard", "30", ZoneClimatique.H3),
			new Departement("Haute-Garonne", "31", ZoneClimatique.H2c),
			new Departement("Gers", "32", ZoneClimatique.H2c),
			new Departement("Gironde", "33", ZoneClimatique.H2c),
			new Departement("Hérault", "34", ZoneClimatique.H3),
			new Departement("Ille-et-Vilaine", "35", ZoneClimatique.H2a),
			new Departement("Indre", "36", ZoneClimatique.H2b),
			new Departement("Indre-et-Loire", "37", ZoneClimatique.H2b),
			new Departement("Isère", "38", ZoneClimatique.H1c),
			new Departement("Jura", "39", ZoneClimatique.H1c),
			new Departement("Landes", "40", ZoneClimatique.H2c),
			new Departement("Loir-et-Cher", "41", ZoneClimatique.H2b),
			new Departement("Loire", "42", ZoneClimatique.H1c),
			new Departement("Haute-Loire", "43", ZoneClimatique.H1c),
			new Departement("Loire-Atlantique", "44", ZoneClimatique.H2b),
			new Departement("Loiret", "45", ZoneClimatique.H1b),
			new Departement("Lot", "46", ZoneClimatique.H2c),
			new Departement("Lot-et-Garonne", "47", ZoneClimatique.H2c),
			new Departement("Lozère", "48", ZoneClimatique.H2d),
			new Departement("Maine-et-Loire", "49", ZoneClimatique.H2b),
			new Departement("Manche", "50", ZoneClimatique.H2a),
			new Departement("Marne", "51", ZoneClimatique.H1b),
			new Departement("Haute-Marne", "52", ZoneClimatique.H1b),
			new Departement("Mayenne", "53", ZoneClimatique.H2b),
			new Departement("Meurthe-et-Moselle", "54", ZoneClimatique.H1b),
			new Departement("Meuse", "55", ZoneClimatique.H1b),
			new Departement("Morbihan", "56", ZoneClimatique.H2a),
			new Departement("Moselle", "57", ZoneClimatique.H1b),
			new Departement("Nièvre", "58", ZoneClimatique.H1b),
			new Departement("Nord", "59", ZoneClimatique.H1a),
			new Departement("Oise", "60", ZoneClimatique.H1a),
			new Departement("Orne", "61", ZoneClimatique.H1a),
			new Departement("Pas-de-Calais", "62", ZoneClimatique.H1a),
			new Departement("Puy-de-Dôme", "63", ZoneClimatique.H1c),
			new Departement("Pyrénées-Atlantiques", "64", ZoneClimatique.H2c),
			new Departement("Hautes-Pyrénées", "65", ZoneClimatique.H2c),
			new Departement("Pyrénées-Orientales", "66", ZoneClimatique.H3),
			new Departement("Bas-Rhin", "67", ZoneClimatique.H1b),
			new Departement("Haut-Rhin", "68", ZoneClimatique.H1b),
			new Departement("Rhône", "69", ZoneClimatique.H1c),
			new Departement("Haute-Saône", "70", ZoneClimatique.H1b),
			new Departement("Saône-et-Loire", "71", ZoneClimatique.H1c),
			new Departement("Sarthe", "72", ZoneClimatique.H2b),
			new Departement("Savoie", "73", ZoneClimatique.H1c),
			new Departement("Haute-Savoie", "74", ZoneClimatique.H1c),
			new Departement("Paris", "75", ZoneClimatique.H1a),
			new Departement("Seine-Maritime", "76", ZoneClimatique.H1a),
			new Departement("Seine-et-Marne", "77", ZoneClimatique.H1a),
			new Departement("Yvelines", "78", ZoneClimatique.H1a),
			new Departement("Deux-Sèvres", "79", ZoneClimatique.H2b),
			new Departement("Somme", "80", ZoneClimatique.H1a),
			new Departement("Tarn", "81", ZoneClimatique.H2c),
			new Departement("Tarn-et-Garonne", "82", ZoneClimatique.H2c),
			new Departement("Var", "83", ZoneClimatique.H3),
			new Departement("Vaucluse", "84", ZoneClimatique.H2d),
			new Departement("Vendée", "85", ZoneClimatique.H2b),
			new Departement("Vienne", "86", ZoneClimatique.H2b),
			new Departement("Haute-Vienne", "87", ZoneClimatique.H1c),
			new Departement("Vosges", "88", ZoneClimatique.H1b),
			new Departement("Yonne", "89", ZoneClimatique.H1b),
			new Departement("Territoire de Belfort", "90", ZoneClimatique.H1b),
			new Departement("Essonne", "91", ZoneClimatique.H1a),
			new Departement("Hauts-de-Seine", "92", ZoneClimatique.H1a),
			new Departement("Seine-Saint-Denis", "93", ZoneClimatique.H1a),
			new Departement("Val-de-Marne", "94", ZoneClimatique.H1a),
			new Departement("Val-d'Oise", "95", ZoneClimatique.H1a),
		};

		#endregion
	}
}
